version: '2'
services:
  cockpit-admin:
    image: cockpit/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  cockpit-api:
    image: cockpit/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev